config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show"
    
  get "/books/:id",   to: "pages#book",       as: :book
  get "/videos/:id",  to: "pages#video_tag",  as: :video_tag
    
  resource :sitemap,  only: :show
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "admin", path_names: {sign_in: 'login', sign_out: 'logout'}

  namespace :admin do
    post 'base/delete_attachment'
        
    resource :dashboard, :path => "/"
    resources :users, :settings, :icons
        
    resources :nodes, as: :root_nodes
    resource :node, path: "*nodes_path" do
      member do
        get :nodes, action: :index
      end
      resource :page, only: [:show, :update]
    end
  end
  
  match "*nodes_path", to: "pages#show", via: [:get, :post]
end

app/models/node.rb
class Node < ActiveRecord::Base
  include RailsSettings::Extend
  extend FriendlyId
  friendly_id :slug_candidates, use: [:scoped, :finders], scope: :node_id

  belongs_to :nodeable, polymorphic: true
  belongs_to :node
  belongs_to :reference_node, class_name: "Node"
  has_many :nodes, dependent: :destroy
  has_many :reference_nodes, class_name: "Node", foreign_key: :reference_node_id
  has_one :page, dependent: :destroy
  
  has_many :node_relations, dependent: :destroy
  has_many :relations, -> { order("nodes.title") }, through: :node_relations
  
  has_many :inverse_node_relations, -> { order("node_relations.weight") }, class_name: "NodeRelation", foreign_key: :relation_id, dependent: :destroy
  has_many :inverse_relations, -> { order("node_relations.weight") }, through: :inverse_node_relations, source: :node

  accepts_nested_attributes_for :nodeable
  accepts_nested_attributes_for :page
  accepts_nested_attributes_for :node
  accepts_nested_attributes_for :nodes, reject_if: -> (c) { c[:name].blank? }, allow_destroy: true

  # attachments
  has_image :image, styles: -> (c) { c.instance.get_image_styles }, default_style: "default", index_style: "thumb", source_file_options: { all: '-background transparent' }
  validates_presence_of :image, if: -> (c) { c.image_required }
  
  has_attachment :attachment, unless: -> (c) { c.attachment_type == "pdf" }
  has_pdf :attachment, if: -> (c) { c.attachment_type == "pdf" }
  validates_presence_of :attachment, if: -> (c) { c.attachment_required }
  validates_attachment_content_type :attachment, content_type: /^video\//, if: -> (c) { c.attachment_type == "video" }, message: "is not a vidio file"
  validates_attachment_content_type :attachment, content_type: /^audio\//, if: -> (c) { c.attachment_type == "audio" }, message: "is not an audio file"
  validates_attachment_content_type :attachment, content_type: /^image\//, if: -> (c) { c.attachment_type == "image" }, message: "is not an image file"
  validates_attachment_content_type :attachment, content_type: [
    "pdf/adobe", "binary/octet-stream", "application/octet-stream", "application/x-pdf", "application/x-octet-stream",
    "application/x-download", "application/download", "application/force-download", "application/pdf", "doesn/matter"
    ], if: -> (c) { c.attachment_type == "pdf" }, message: "is not a PDF file"

  scope :actives, -> { where(active: true) }

  before_save do
    if path.blank? || slug_changed?
      get_path
      update_paths
    end
    if name_changed? && name?
      name = name.to_s.strip
    end
    
    if ['social_link', 'buy_link'].include?(kind) && self.new_record?
      self.weight = Node.where(kind: kind).count + 1
    end
    
    if self.image? && (width_changed? || height_changed?)
      self.image = self.image
    end
  end
      
  def update_paths
    return unless id?
    nodes.each do |node|
      # node.node = self
      node.get_path
      node.save
      node.update_paths
    end
  end
  
  #
  #
  #
  def child(kind, un=nil)
    (un.nil? ? nodes.find_by_kind(kind) : nodes.find_by_kind_and_un(kind, un))
  end

  def children_references(kind, un=nil)
    child(kind, un).nodes.references(:reference_node).includes(:reference_node).order(:weight).where(active: true, "reference_nodes_nodes.active" => true).collect{|c| c.reference_node}
  end

  def children(kind=nil, un=nil)
    if kind.nil? && un.nil?
      nodes.where(active: true).order(:weight)
    else
      child(kind, un).nodes.where(active: true).order(:weight)
    end
  end
  
  # related nodes
  def related_ids
    (node_relations.pluck(:relation_id, :weight) + inverse_node_relations.pluck(:node_id, :inverse_weight)).sort_by{ |r| r[1] }.map{ |r| r[0] }.uniq
  end
  
  def related_videos
    ids = related_ids
    if ids.present?
      Node.find_by_un(:videos).children.where("id IN (#{ ids.join(',') })").sort_by{ |v| ids.index v.id }
    else
      []
    end
  end
  
  def related_tags(ids=nil)
    ids ||= related_ids
    if ids.present?
      Node.find_by_un(:tags).children.where("id IN (#{ ids.join(',') })").sort_by{ |p| ids.index p.id }
    else
      []
    end
  end
  
  def get_social(un)
    if kind == 'footer'
      case un
      when :fb
        link_text
      when :tw
        link_url
      when :in
        description
      when :yt
        email
      end
    end
  end

  #
  # Slug generation
  #
  def slug_candidates
    [:name_slug, :name_and_sequence_slug]
  end

  def name_slug
    if name != "default" || kind == "page"
      ((name.present? ? name : nil) || (title.present? ? title : nil) || (link_text.present? ? link_text : nil) || un || kind).to_s
    else
      kind.to_s
    end
  end

  def name_and_sequence_slug
    if name != "default" || kind == "page"
      slug = ((name.present? ? name : nil) || (title.present? ? title : nil) || (link_text.present? ? link_text : nil) || un || kind).to_s.parameterize
    else
      slug = kind.to_s.parameterize
    end
    sequence = (node_id.nil? ? Node.where(node_id: nil) : node.nodes).where("slug like '#{slug}-%'").count + 2
    "#{slug}-#{sequence}"
  end

  def should_generate_new_friendly_id?
    (name.present? && name_changed?) || (title.present? && title_changed?) || (link_text.present? && link_text_changed?) || slug.blank?
  end

  def get_path
    n = self
    p = [slug]
    while n.node
      n = n.node
      p << n.slug
    end
    self.path = p.reverse.join("/")
  end

  def to_param
    if path.blank?
      get_path
      save
    end
    path
  end

  #
  # Image styles
  #
  def get_image_styles
    def stylefor(width, height)
      if width == 0
        return if height == 0
        image_max ? "x#{height}>" : "x#{height}"
      elsif height == 0
        image_max ? "#{width}>" : "#{width}"
      else
        image_max ? "#{width}x#{height}>" : "#{width}x#{height}#"
      end
    end
    {
      thumb: stylefor(width / 2, height / 2),
      default: stylefor(width, height) || "",
      retina: stylefor(width * 2, height * 2)
    }.reject{|k, v| v.nil?}
  end
end

app/controllers/admin/nodes_controller.rb
class Admin::NodesController < Admin::BaseController
  resources Node,
    belongs_to: -> (c) { c.load_parents },
    datatables: {
      fields: [:image, :node_date, :name, :title, :path, :slug, :un, :kind, :image_alt, :link_url, :link_text, :width, :height, :image_max, :reference_node_id, :link_new_window, :description, :template, :email, :attachment],
      row: -> (row, res) {
        res[:reference_node] = row.reference_node.attributes if row.reference_node
        res[:date] = row.node_date.try(:strftime, '%B %d, %Y')
        res[:tags] = row.related_tags.map(&:name).join(", ") if row.kind == 'video'
        res[:attachment_url] = row.attachment? ? row.attachment.url : '';
      },
      search: [:name, :title, :slug, :description, :link_text, :node_date],
      filter: :collection
    }

  def load_parents
    @nodes_hierarchy = []
    if params[:nodes_path]
      @node = node = Node.find_by_path(params[:nodes_path])
      raise ActiveRecord::RecordNotFound unless node
      @nodes_hierarchy << @node
      @page_node = node if node.page
      while node.node
        node = node.node
        @page_node = node if @page_node.nil? && node.page
        @nodes_hierarchy << node
      end
      @node_info = Site.get(@node)
      if @node_info
        @max_active = @node_info[:max_active]
        @max_count = @node_info[:max_count]
      end
    end
    @node
  end

  def collection(m)
    m = m.where(kind: params[:kind]) if params[:kind].present?
    m = m.where(un: params[:un]) if params[:un].present?
    m
  end

  def before_save
    if params[:node] && params[:node][:image] && params[:node][:image] == ''
      @node.image = nil
    end
    if params[:node] && params[:node][:attachment] && params[:node][:attachment] == ''
      @node.attachment = nil
    end
    if @node.kind == 'module'
      @template_was = @node.template
    end
  end

  def after_save
    if @node.valid?
      if @node.node && @node.node.kind == "genericpages" && @node.node.node.nil?
        @node.build_reference_node(kind: "alias", reference_node: @node) unless @node.reference_node
        @node.reference_node.name = @node.name || @node.title
        @node.reference_node.save
        @node.save
      end
      
      if params[:node] && params[:node][:inverse_relation_ids]
        params[:node][:inverse_relation_ids].reject(&:blank?).each_with_index do |id, index|
          if nr = @node.inverse_node_relations.find_by_node_id(id)
            nr.update_attributes(weight: index + 1)
          end
        end
      end
      
      if @node.kind == 'module' && @node.image?
        if @template_was && @template_was != @node.template
          @node.image.reprocess!
        end
      end
      
      params[:related_nodes] = [] unless params[:related_nodes]
      
      # add / remove tags
      if params[:related_nodes] && params[:related_nodes].is_a?(Array)
        new_relations = params[:related_nodes].collect{|c| c.to_i}
        old_relations = @node.related_ids

        to_remove = old_relations - new_relations
        to_add = new_relations - old_relations

        to_remove.each do |c|
          @node.node_relations.where(relation_id: c).delete_all
          @node.inverse_node_relations.where(node_id: c).delete_all
        end
        to_add.each do |c|
          @node.node_relations.create(relation_id: c)
        end
        
        # set weights
        Node.transaction do
          @node.node_relations.each do |direct_relation|
            weight = params[:related_nodes].index(direct_relation.relation_id.to_s).to_i + 1
            direct_relation.update_attributes(weight: weight) unless direct_relation.weight == weight
          end
          @node.inverse_node_relations.each do |inverse_relation|
            inverse_weight = params[:related_nodes].index(inverse_relation.node_id.to_s).to_i + 1
            inverse_relation.update_attributes(inverse_weight: inverse_weight) unless inverse_relation.inverse_weight == inverse_weight
          end
        end
      end
            
      Site.node_created(@node) if params[:action] == "create"

      flash[:notice] = "Successfully saved!"
      if @node.node && !@node.page && !@node.node.page && !(@node.node.node.blank? && @node.node.kind == "global")
        redirect_to admin_node_path(@node.node)
      else
        redirect_to admin_node_path(@node)
      end
    else
      render action: :show
    end
  end
  
  def before_destroy
    if @node.kind == 'business' && featured = Node.find_by_un('featured_businesses').nodes.find_by(kind: :featured_business, reference_node_id: @node.id)
      featured.destroy
    elsif @node.kind == 'featured_business' && @node.reference_node
      @node.reference_node.update_attributes(link_new_window: false)
    end
  end
end

app/helpers/admin/nodes_helper.rb
module Admin::NodesHelper
  def build_tree(node)
    res = []
    node.order(:weight).each do |n|
      has_page = n.page.present?
      res << "<li style='" + (n.active ? "" : "opacity:0.5") + "'>"
      res << "<b>" if has_page
      res << "<a href='" + admin_node_path(n) + "'>" + h(n.name) + " (" + h(n.kind) + (n.un.present? ? ": <small>" + n.un + "</small>" : "") + ")"
      res << "</a>"
      res << " <span style='color:red'>-&gt; <a href='" + admin_node_path(n.reference_node) + "'>" + h(n.reference_node.name) + " (" + h(n.reference_node.kind) + ")</span>" if n.reference_node
      res << "</b>" if has_page
      res << build_tree(n.nodes)
      res << "</li>"
    end
    res.length > 0 ? "<ol>" + res.join + "</ol>" : ""
  end
  
  def get_tag_selectables(all=[], tags=[])
    existing = all.select{ |row| tags.include?(row[1]) }.sort_by{ |row| tags.index row[1] }
    other = all - existing
    return (existing + other)
  end
end

app/views/admin/nodes/show/_all_modules_item.haml
- @node.template||= 0

= admin_form_for [:admin, @node], url: @node.new_record? ? admin_node_path(@node.node) : admin_node_path(@node), html: {multipart: true} do |f|
  = f.hidden_field :kind, value: :module
  
  = f.radio_buttons :template, { "Video/Upcoming Event" => 0, "Featured Book Slider" => 1, "Photo Slider" => 2, "Social Feed" => 3 }, onchange: "onTypeChange(this.value)", field_class: "col-md-9"
  
  = f.text_field :name, required: true, help_inline: 'Set unique admin-only name for organizational purposes.'
  
  .tpl.tpl0
    = f.hidden_field :width, value: 457
    = f.hidden_field :height, value: 0
    = f.image_upload :image, required: true, width: 457
    = f.text_field :image_alt, label: 'Image Alt Text', help_inline: "Set Image Alt Text", field_class: 'col-md-4'
    
    = f.admin_fields_for @node.settings do |p|
      = p.text_area :video_embed_code, label: "Video Embed Code", help_inline: "Set Video Embed Code", field_class: "col-md-10"
    
    = f.text_field :title, help_inline: "Set Title"
    = f.text_area :description, help_inline: "Set Description", class: "ckeditor", field_class: "col-md-10"
        
  .tpl.tpl3
    = f.text_field :link_text, label: "Facebook URL", help_inline: "Set Facebook URL"
    = f.text_field :email, label: "Twitter Handle", help_inline: "Set Twitter Handle"

  = f.actions
  - content_for :script, f.validate

- content_for :script do
  :javascript
    function onTypeChange(val) {
      $('.tpl').hide();
      $('.tpl input').attr('disabled', true);
      $('.tpl' + val).show();
      $('.tpl' + val + ' input').removeAttr('disabled');
    }
    onTypeChange(#{@node.template});

app/views/admin/nodes/show/_book_images.haml
:css
  #data-table tr td {max-height:200px; overflow: hidden;}
  #data-table tr td .slide {max-height:200px; overflow: hidden; position: relative; text-align: center;}
  #data-table tr td .slide strong {text-transform: uppercase;}
  #data-table tr td .slide div {position:absolute; background:#eee; left: 0; width:736px; height:67px; padding:8px; opacity:0.6; margin-top:133px; white-space: normal; overflow: hidden;}

.col-md-12
  -# .clearfix.margin-bottom-10
    Slideshow Timeout:
    = link_to "", "", "data-value" => @node.settings.slideshow_timeout, :id => "slideshow_timeout"
      
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus

  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Image", mRender: function(data, type, row) {
          return "<div class='slide'><img src='" + row.image + "' style='max-width: 600px; max-height: 250px;' /></div>";
        }},
        {sTitle: "Link", bSortable: false, mRender: function(data, type, row){
          if (row.link_url.length) {
            return '<a href="' + row.link_url + '" target="_blank">' + (row.link_url.length > 50 ?  (row.link_url.substr(0, 50) + '...') : row.link_url) + '</a><br /><em>' + (row.link_new_window ? 'new' : 'same') +  ' window</em>';
          } else {
            return '';
          }
        }},
        d.columns.actions()
      ]
    });
    
-#
    $('#slideshow_timeout').editable({
      inputclass: 'form-control input-medium',
      type: "text",
      title: "Slideshow Timeout in seconds (default: 1)",
      pk: 1,
      name: "slideshow_timeout",
      url: "/admin/settings?node_id=#{@node.id}",
      validate: function(v) {if (isNaN(v*1) || v*1 != parseFloat(v)) return "Number required";}
    });

app/views/admin/nodes/show/_books.haml
.col-md-12      
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus

  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Image", mRender: function(data, type, row) {
          return "<img src='" + row.image + "' style='max-width: 600px; max-height: 250px;' />";
        }},
        {sTitle: "Text", mRender: function(data, type, row) {
          return "<h4><strong>" + (row.title || '') + "</strong></h4>" + (row.description || '');
        }},
        {sTitle: "Has Page", sClass: "center", mRender: function(data, type, row) {
          if (row.link_new_window) {
            return '<span class="fa fa-check" style="font-size: 20px; color: green"></span> <strong style="font-size: 14px">Yes</strong>';
          } else {
            return '<span class="fa fa-times" style="font-size: 20px; color: red"></span> <strong style="font-size: 14px">No</strong>';
          }
        }},
        d.columns.actions()
      ]
    });

app/views/admin/nodes/show/_buy_link_fields.haml
.fields.row
  = f.hidden_field :kind, value: :buy_link
  = f.hidden_field :weight, class: 'item_weight'
  
  .col-md-4{ style: "padding-right: 0" }= f.text_field :name, label: "", placeholder: "Link Text", field_class: "col-md-12"
  .col-md-6
    .col-md-10= f.text_field :link_url, label: "", placeholder: 'Link URL', field_class: "col-md-12"
    .col-md-2.checkbox_field= f.check_box :link_new_window, label: '<span class="fa-external-link"></span>'.html_safe, field_class: "col-md-12"
  %span.fa.fa-sort
  %span.remove= link_to_remove_fields '<span class="fa fa-times">'.html_safe, f

app/views/admin/nodes/show/_generic_pages.haml
.col-md-12
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus
      
  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      aaSorting: [1, 'asc'],
      aoColumns: [
        {sTitle: "Title", mDataProp: "title"},
        {sTitle: "URL", mRender: function(data, type, row) {
          return '<a href="/' + row.slug + '">/' + row.slug + '</a>';
        }},
        d.columns.actions()
      ]
    });

app/views/admin/nodes/show/_images.haml
:css
  #data-table tr td {max-height:200px; overflow: hidden;}
  #data-table tr td .slide {max-height:200px; overflow: hidden; position: relative; text-align: center;}
  #data-table tr td .slide strong {text-transform: uppercase;}
  #data-table tr td .slide div {position:absolute; background:#eee; left: 0; width:736px; height:67px; padding:8px; opacity:0.6; margin-top:133px; white-space: normal; overflow: hidden;}

.col-md-12
  -# .clearfix.margin-bottom-10
    Slideshow Timeout:
    = link_to "", "", "data-value" => @node.settings.slideshow_timeout, :id => "slideshow_timeout"
      
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus

  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Image", mRender: function(data, type, row) {
          return "<div class='slide'><img src='" + row.image + "' style='max-width: 600px; max-height: 250px;' /></div>";
        }},
        d.columns.actions()
      ]
    });

-#    
    $('#slideshow_timeout').editable({
      inputclass: 'form-control input-medium',
      type: "text",
      title: "Slideshow Timeout in seconds (default: 1)",
      pk: 1,
      name: "slideshow_timeout",
      url: "/admin/settings?node_id=#{@node.id}",
      validate: function(v) {if (isNaN(v*1) || v*1 != parseFloat(v)) return "Number required";}
    });

app/views/admin/nodes/show/_images_item.haml
:css
  .fileinput .thumbnail img { max-width: 400px !important; max-height: 400px !important; }
  
= admin_form_for [:admin, @node], url: @node.new_record? ? admin_node_path(@node.node) : admin_node_path(@node), html: {multipart: true} do |f|
  = f.hidden_field :kind, value: :image
  
  = f.hidden_field :width, value: 246
  = f.hidden_field :height, value: 246
  
  = f.image_upload :image, removeable: false, required: true, width: 246, height: 246
  = f.text_field :image_alt, label: "Image Alt Text", help_inline: "Set Image Alt Text", field_class: "col-md-4"
    
  = f.actions
  - content_for :script, f.validate

app/views/admin/nodes/show/_links_item.haml
  
= admin_form_for [:admin, @node], url: @node.new_record? ? admin_node_path(@node.node) : admin_node_path(@node), html: {multipart: true} do |f|
  
  = f.text_field :name, label: "Link Text", help_inline: "Set Link Text", required: true
  = f.text_field :link_url, label: "Link URL", help_inline: "Set Link URL", required: true do
    = f.check_box :link_new_window, label: "Open the link in a new window"
      
  = f.actions
  - content_for :script, f.validate

app/views/admin/nodes/show/_modules.haml
.col-md-12
  .table-toolbar
    - modules = Node.find_by_path("global/modules").nodes.where(active: true).where.not("id in (?)", @node.nodes.pluck(:reference_node_id) + [0]).order(:name).pluck(:name, :id)
    - if modules.count > 0
      - @new_node = @node.nodes.build
      = admin_form_for [:admin, @new_node], url: admin_node_path(@node), label_class: "col-md-2", field_class: "col-md-4" do |f|
        = f.hidden_field :name, value: "module"
        .col-md-6
          = f.select :reference_node_id, modules, label: "Module"
        %button.btn.btn-success
          Add
          %i.fa-plus
  %table#data-table


- content_for :script do
  :javascript
    $("#node_reference_node_id").select2({width: 300});
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      onDelete: function() {self.location = '#{admin_node_path(@node)}'},
      aoColumns: [
        {sTitle: "Name", mRender: function(data, type, row) {
          return row.reference_node && row.reference_node.name;
        }},
        d.columns.actions({edit: false})
      ]
    });

app/views/admin/nodes/show/_news_items.haml
.col-md-12
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus
      
  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Logo", bSortable: false, mRender: function(data, type, row){
          if (row.image != "/images/default/missing.png")
            return "<div class='slide'><img src='" + row.image + "' style='max-height: 150px;' /></div>";
          else
            return '';
        }},
        {sTitle: "Link", bSortable: false, mRender: function(data, type, row){
          var url = row.template == 1 ? row.attachment_url : row.link_url;
          var link_text = url ? (url.length > 50 ? (url.substr(0, 50) + '...') : url) : '';
          
          if (url.length) {
            return (row.template == 1 ? 'PDF: ' : 'URL: ') + '<a href="' + url + '" target="_blank">' + link_text + '</a><br />' + (row.template == 1 ? '' : ('<em>' + (row.link_new_window ? 'new' : 'same') +  ' window</em>'));
          } else {
            return '';
          }
        }},
        d.columns.actions()
      ]
    });

app/views/admin/nodes/show/_praise_items.haml
.col-md-12
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus
      
  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Name", mDataProp: "name"},
        d.columns.actions()
      ]
    });

app/views/admin/nodes/show/_praise_items_item.haml
= admin_form_for [:admin, @node], url: @node.new_record? ? admin_node_path(@node.node) : admin_node_path(@node), html: {multipart: true} do |f|
  = f.hidden_field :kind, value: :praise_item
  
  = f.field :state do
    = f.check_box :active
  
  = f.text_field :name, required: true, help_inline: "Set Name for organizational purposes in admin"
  = f.text_area :description, help_inline: "Set Text", class: "ckeditor", field_class: "col-md-10"
  
  = f.actions
  - content_for :script, f.validate
    

app/views/admin/nodes/show/_videos.haml
.col-md-12
  .table-toolbar
    .btn-group
      %a.btn.btn-success{ :href => new_admin_node_path(@node) }
        Add New
        %i.fa-plus
      
  %table#data-table

- content_for :script do
  :javascript
    var d = datatables('#data-table', '#{nodes_admin_node_path(@node)}');
    d.init({
      reordering: true,
      aoColumns: [
        {sTitle: "Name", mDataProp: "name"},
        {sTitle: "Tags", mDataProp: "tags"},
        d.columns.actions()
      ]
    });