config/routes.rb
Rails.application.routes.draw do
  root to: "pages#show"
    
  get "/books/:id",   to: "pages#book",       as: :book
  get "/videos/:id",  to: "pages#video_tag",  as: :video_tag
    
  resource :sitemap,  only: :show
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: "admin", path_names: {sign_in: 'login', sign_out: 'logout'}

  namespace :admin do
    post 'base/delete_attachment'
        
    resource :dashboard, :path => "/"
    resources :users, :settings, :icons
        
    resources :nodes, as: :root_nodes
    resource :node, path: "*nodes_path" do
      member do
        get :nodes, action: :index
      end
      resource :page, only: [:show, :update]
    end
  end
  
  match "*nodes_path", to: "pages#show", via: [:get, :post]
end

app/views/layouts/admin.html.erb
<% menu = menu_builder %>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
   <meta charset="utf-8" />
   <title><%= @page_title || ("Admin " + Site.site_name) %></title>
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta name="MobileOptimized" content="320" />
   <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
   <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
   <link href="/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
   <link href="/admin/dist/css/admin.min.css" rel="stylesheet" type="text/css" />
   <link href="/admin/themes/jo.css" rel="stylesheet" type="text/css" />
   <!--link href="/admin/main.css" rel="stylesheet" type="text/css" /-->
   <link href="/admin/assets/fonts/font.css" rel="stylesheet" type="text/css" />
   
   <%= stylesheet_link_tag "admin" %>
   <%= csrf_meta_tag %>
</head>
<body class="page-boxed">
  <!-- BEGIN HEADER -->
  <div class="header navbar navbar-static-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="header-inner container">
      <!-- BEGIN LOGO -->  
      <div class="page-logo">
        <a href="/admin"><%= image_tag("/admin/logo.png", class: "img-responsive", alt: "logo") %></a>
      </div>
      <!-- END LOGO -->
      <!-- BEGIN RESPONSIVE MENU TOGGLER --> 
			<a href="javascript:;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<img src="/admin/assets/img/menu-toggler-black.png" alt="" />
			</a> 
			<!-- END RESPONSIVE MENU TOGGLER -->
      <!-- BEGIN TOP NAVIGATION MENU -->
      <ul class="nav navbar-nav pull-right">
        <li class="devider">&nbsp;</li>
        <!-- BEGIN USER LOGIN DROPDOWN -->
        <li class="dropdown user">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <!--img alt="" src="/assets/img/avatar3_small.jpg" style='opacity:0'/-->
            <span class="username"><%= current_user.username %></span>
            <i class="fa-angle-down"></i>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= edit_admin_user_path(current_user) %>"><i class="fa-user"></i> Account</a></li>
            <li class="divider"></li>
            <li><a href="/admin/logout" data-method="delete"><i class="fa-key"></i> Log Out</a></li>
          </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->
      </ul>
      <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END TOP NAVIGATION BAR -->
  </div>
  <!-- END HEADER -->
  <div class="clearfix"> </div>

  <!-- BEGIN CONTAINER -->
  <div class="container">
    <div class="page-container">
      <div class="page-sidebar-wrapper">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar navbar-collapse collapse">
          <!-- BEGIN SIDEBAR MENU -->        
          <ul class="page-sidebar-menu">
            <li>
              <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
              <div class="sidebar-toggler"></div>
              <div class="clearfix"></div>
              <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <%= menu %>
          </ul>
          <!-- END SIDEBAR MENU -->
        </div>
        <!-- END SIDEBAR -->
      </div>

      <div class="page-content-wrapper">
        <!-- BEGIN PAGE -->
        <div class="page-content">
          <!-- BEGIN PAGE HEADER-->
          <!-- BEGIN PAGE TITLE & BREADCRUMB-->
          <h3 class="page-title">
            <%= @title %>
            <% if @title_small %>
              <small><%= @title_small %></small>
            <% end %>
          </h3>
          <div class="page-bar">
            <ul class="page-breadcrumb">
              <%= breadcrumbs %>
            </ul>
            <div class="page-toolbar">
              <%= yield :page_toolbar %>
              <% if @page_node && @page_node.active && path_for(@page_node).present? %>
                <a href="<%= path_for(@page_node) %>" target="_blank" class="pull-right tooltips btn btn-fit-height btn-info">
                  View Page
                </a>
              <% end %>
            </div>
          </div>

          <div class="row">
            <!-- END PAGE TITLE & BREADCRUMB-->
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <strong>Success!</strong>
                <%= flash[:notice] %>
              </div>
            <% end %>
            <% if flash[:error] %>
              <div class="alert alert-danger">
                <strong>Error!</strong>
                <%= flash[:error] %>
              </div>
            <% end %>
          </div>
          <!-- END PAGE HEADER-->

          <!-- BEGIN PAGE CONTENT-->
          <div class="row">
            <%= yield %>
          </div>
          <!-- END PAGE CONTENT-->
        </div>
        <!-- END PAGE -->
      </div>
    </div>

    <div class="footer">
      <div class="footer-inner">
      </div>
      <div class="footer-tools">
        <span class="go-top">
        <i class="fa-angle-up"></i>
        </span>
      </div>
    </div>
  </div>
  <!-- END CONTAINER -->
  
  <script>window.CKEDITOR_BASEPATH = "/admin/ckeditor/";</script>
  <%= javascript_include_tag "admin", "/admin/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min", "ui.multiselect", "/admin/dist/js/admin.min", "/admin/main", "/admin/ckeditor/ckeditor" %>
  <script>App.init();</script>
  <%= yield :script %>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html{ lang: "en" }
  %head
    %title= get_title
    %meta{ charset: "UTF-8" }/
    %meta{ "http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1" }/
    %meta{ name: "SKYPE_TOOLBAR", content: "SKYPE_TOOLBAR_PARSER_COMPATIBLE" }/
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }/
    %meta{ name: "viewport", content: meta_viewport }/
    - if @page
      %meta{ name: "description", content: @page.meta_description }/
      %meta{ name: "keywords", content: @page.meta_keywords }/
        
    - cache :icons do
      - Icon.all.each do |icon|
        - next if icon.un == "favicon" || !icon.icon?
        %link{ rel: icon.un.gsub("_", "-"), sizes: "#{icon.width}x#{icon.height}", href: icon.filename }/
        
    %link{ rel: "shortcut icon", href: "/favicon.ico", type: "image/x-icon" }/
    
    = stylesheet_link_tag "application", media: "all"
    /[if lte ie 8]
      = stylesheet_link_tag "ie8", media: "all"
    
    - @nodes ||= Node.joins(:page).where(node_id: nil, active: true)
    :javascript
      var is_mobile = #{(@is_mobile || browser.mobile?).to_json}, is_ios = #{((browser.tablet? || browser.mobile?) && browser.safari?).to_json}, is_tablet = #{browser.tablet?.to_json}, is_ie8 = #{browser.ie8?.to_json};
    
    = javascript_include_tag "application", media: 'all'
          
    = csrf_meta_tags
    
    != Settings.webmaster
    
    = yield :head
    
    - if browser.tablet? || browser.mobile?
      :css
        * {
          -webkit-touch-callout: none;
          -webkit-user-select: none;
          -khtml-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
        }
        input {
          -webkit-touch-callout: initial;
          -webkit-user-select: initial;
          -khtml-user-select: initial;
          -moz-user-select: initial;
          -ms-user-select: initial;
          user-select: initial;
        }
    
  %body{ class: body_class }
    #fb-root
    :javascript        
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '492591327588665',
          cookie     : true,  // enable cookies to allow the server to access the session
          xfbml      : true,  // parse social plugins on this page
          version    : 'v2.2' // use version 2.2
        });
      };
        
      // Load the SDK asynchronously
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      
    #page_wrapper
      #page_wrapper2

        #header_wrapper
          %header
            %a.h_logo{ href: '/' } Alondra Nelson
            %a.show_nav{ href: '#' }
              %span
              
            .h_nav_wrapper
              .h_nav
                %a.close{ href: '#' }
                %ul
                  %li{ class: cp(/\A\/$/) }= link_to "Home", "/"
                  %li{ class: cp(/^\/about/) }= link_to "About", "/about"
                  %li{ class: cp(/^\/books/) }= link_to "Books", "/books"
                  %li{ class: cp(/^\/events/) }= link_to "Events", "/events"
                  - if blog_node = Node.find_by_un(:blog_link)
                    - if blog_node.active && blog_node.link_url?
                      %li= link_to "Blog", blog_node.link_url, target: "_blank"
                  %li{ class: cp(/^\/videos/) }= link_to "Videos", "/videos"
                  %li.last{ class: cp(/^\/contact/) }= link_to "Contact", "/contact"
                  
        %main= yield
        
    #footer_wrapper            
      %footer
        .f_top
          - footer = Node.find_by_un(:footer)
          - footer_settings = footer.settings
          - (1..4).each do |i|
            - if footer_settings.send("column#{i}").present?
              %div!= footer_settings.send("column#{i}")
                
          .f_social
            %h4 Get Social
            %ul
              - [:fb, :tw, :in, :yt].each do |s|
                - if footer.get_social(s).present?
                  %li= link_to "", footer.get_social(s), target: "_blank", class: "soc #{s}"
    
    #video_modal
      .modal_overlay
      %a.close{ href: '#' }
      .video
      
    = yield :script
    
    != Settings.google_analytics
    

app/views/layouts/browser_error.haml
!!!
%html{ lang: "en" }
  %head
    %title Galcon Construction
    %meta{ charset: "UTF-8" }/
    %meta{ "http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1" }/
    %meta{ name: "SKYPE_TOOLBAR", content: "SKYPE_TOOLBAR_PARSER_COMPATIBLE" }/
    %meta{ name: "viewport", content: meta_viewport }/
    %link{ rel: "shortcut icon", href: "favicon.ico", type: "image/x-icon" }/
    
    = stylesheet_link_tag "application", media: "all"
    
    = csrf_meta_tags
    
    :css
      .logoAndMenuWrapper { margin: 11px }
      .contacts-info { height: 300px; margin-bottom: 20px; }
      .contacts-text { width: auto }

  %body.gBody
    .pageWrapper
      .logoAndMenuWrapper
        = image_tag "logo.jpg", alt: "Galcon Construction", width: 130
      
    = yield
    

app/views/layouts/exception.html.erb
<!DOCTYPE HTML>
<html lang="en" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
  <meta property="og:url" content=<%= request.url.inspect %>>
  <% cache controller: params[:controller], action: params[:action], id: params[:id], action_suffix: "headers" do -%>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <%= meta_tags %>
    <%= yield :head -%>
    <!--[if lte ie 8]>
      <%= stylesheet_link_tag "ie8", media: "all" %>
    <![endif]-->
    <!--[if lte ie 9]>
      <%= stylesheet_link_tag "ie9", media: "all" %>
    <![endif]-->
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <% end -%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="page_wrapper">
    <div id="page_wrapper2">
      <header id="page_header">
        <a class="logo" title="Books and Authors" href="/"><%= image_tag("logo.png", alt: "logo") %></a>
        <nav class="h_nav">
        </nav>
      </header>
      <%= yield %>
    </div>
  </div>
</body></html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>Login</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	<meta name="MobileOptimized" content="320">
  <link href="/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="/admin/dist/css/admin.min.css" rel="stylesheet" type="text/css" />
  <link href="/admin/assets/fonts/font.css" rel="stylesheet" type="text/css" />
	<link href="/admin/assets/css/pages/login.css" rel="stylesheet" type="text/css" />
  <link href="/admin/main.css" rel="stylesheet" type="text/css" />
	<%= csrf_meta_tag %>
</head>
<body class="login">
	<div class="logo">
		<img src="/admin/logo.png" alt="" />
	</div>
	<div class="content">
	  <%= yield %>
	</div>
		
  <%= javascript_include_tag "admin", "/admin/dist/js/admin.min", "/admin/main" %>
  <script>App.init();</script>
  <%= yield :script %>
</body>
</html>